---
- role: Reviewer
  program: Nature Electronics
- role: Reviewer
  program: Advanced Materials
- role: Reviewer
  program: Joule (Cell sister journal)
- role: Reviewer
  program: Device (Cell sister journal)
- role: Reviewer
  program: ACM IMWUT (Proc. ACM Interact. Mob. Wearable Ubiquitous Technol.)
- role: Reviewer
  program: ACM UIST
- role: Reviewer
  program: National Science Review
- role: Scientific Committee
  program: IEEE IGARSS 2024 (Int. Geosci. Remote Sens. Symp.)
- role: Reviewer
  program: IEEE Transactions on Industrial Electronics
- role: Reviewer
  program: IEEE Transactions on Power Electronics
- role: Reviewer
  program: IEEE Transactions on Microwave Theory and Techniques
- role: Reviewer
  program: IEEE Transactions on Wireless Communications
- role: Reviewer
  program: IEEE Transactions on Mobile Computing
- role: Reviewer
  program: IEEE Internet of Things Journal
- role: Reviewer
  program: IEEE Antennas and Wireless Propagation Letters
- role: Reviewer
  program: IEEE Microwave and Wireless Components Letters
- role: Reviewer
  program: IEEE Pervasive Computing
- role: Reviewer
  program: IEEE Journal of Emerging and Selected Topics in Power Electronics
- role: Reviewer
  program: IEEE Open Journal of the Industrial Electronics Society
- role: Reviewer
  program: IEEE Open Journal of Industry Applications
- role: Reviewer
  program: IEEE Access
- role: Reviewer
  program: ACS Applied Electronic Materials
- role: Reviewer
  program: Scientific Reports
- role: Reviewer
  program: MDPI Sensors
- role: Reviewer
  program: MDPI Energies
- role: Reviewer
  program: MDPI Sustainablility
- role: Reviewer
  program: MDPI Magnetochemistry
- role: Reviewer
  program: PeerJ Computer Science
- role: Reviewer
  program: ROBOMECH Journal
