name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # Schedule to run daily at 2 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: bundle install

    - name: Fetch data from Google Sheets
      run: ruby _scripts/get_data.rb

    - name: Check for changes
      id: check_changes
      run: |
        # Check if the _data/publications.yml file has changed
        git diff --exit-code _data/publications.yml || echo "Changes detected"
        git diff --quiet _data/publications.yml || echo "::set-output name=changes::true"
      shell: bash

    - name: Create Pull Request
      if: steps.check_changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Update publications data'
        branch: update-publications-data-branch
        title: 'Update publications data'
        body: 'This pull request updates the publications data.'