on:
  schedule:
    - cron: '0 3 * * *' # Run on 12:00 JST / 3:00 UTC
  workflow_dispatch:

name: Check links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://www.takuyasasatani.com
          cmd_params: '--buffer-size=32768 --max-connections=10 --color=always --timeout=20--header="User-Agent:curl/7.54.0"'
