name: Check Internal Link and Link Format

on:
  schedule:
    - cron: '0 3 * * *' # Run on 12:00 JST / 3:00 UTC
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Linkchecker
      run: |
        pip install linkchecker

    - name: Run Linkchecker
      run: |
        linkchecker https://www.takuyasasatani.com\
