name: Update Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *' # Schedule to run daily at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Install dependencies
      run: bundle install

    - name: Fetch data from Google Sheets
      run: ruby _scripts/fetch_publications.rb

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add _data/publications.yml
        git commit -m 'Update publications data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}